defaults: &defaults
  working_directory: /opt/iroha
  environment:
    IROHA_HOME: /opt/iroha
    IROHA_BUILD: /opt/iroha/build

version: 2

jobs:
  build:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
      - image: postgres:9.5
      - image: redis:3.2.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-linux-{{ .Branch }}
            - build-cache-linux-
          paths:
            - ~/.ccache
      - run:
          name: ccache setup
          command: |
            ccache --max-files=0
            ccache --max-size=1G
      - run:
          name: cmake
          command: cmake -DCOVERAGE=ON -H$IROHA_HOME -B$IROHA_BUILD
      - run:
          name: make
          command: |
            cmake --build $IROHA_BUILD -- -j4
      - save_cache:
          key: build-cache-linux-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.ccache
      - save_cache:
          key: build-cache-linux-{{ epoch }}
          paths:
            - ~/.ccache
      - run: ccache --show-stats
      - run:
          name: unit tests, generate xunit-*.xml
          command: cmake --build $IROHA_BUILD --target test
      - run:
          name: coverage info
          command: cmake --build $IROHA_BUILD --target gcovr
      - run:
          name: cppcheck
          command: cmake --build $IROHA_BUILD --target cppcheck
      - persist_to_workspace:
          root: /opt/iroha/build
          paths:
            - compile_commands.json
            - reports



  # used to push info about issues to github
  sonar-pr:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - sonar-
      - attach_workspace:
          at: /opt/iroha/build
      - run:
          name: codecov.io
          command: bash <(curl -s https://codecov.io/bash) -f $IROHA_BUILD/reports/gcovr.xml || echo "Codecov did not collect coverage reports"
      - run:
          name: execute sonar-scanner to analyze PR
          command: >
            if [ ! -z "$SONAR_TOKEN" ] && \
              [ ! -z "$SORABOT_TOKEN" ] && \
              [ ! -z "$CIRCLE_BUILD_NUM" ] && \
              [ ! -z "$CI_PULL_REQUEST" ]; then
              sonar-scanner \
                -Dsonar.github.disableInlineComments \
                -Dsonar.github.repository="hyperledger/iroha" \
                -Dsonar.analysis.mode=preview \
                -Dsonar.login=${SONAR_TOKEN} \
                -Dsonar.projectVersion="${CIRCLE_BUILD_NUM}" \
                -Dsonar.github.oauth="${SORABOT_TOKEN}" \
                -Dsonar.github.pullRequest="$(echo $CI_PULL_REQUEST | egrep -o "[0-9]+")"
            else
              echo "required env vars not found"
            fi
      - save_cache:
          key: sonar-{{ epoch }}
          paths:
            - ~/.sonar


  # executed only for develop, master and release branches
  sonar-release:
    <<: *defaults
    docker:
      - image: hyperledger/iroha-docker-develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - sonar-
      - attach_workspace:
          at: /opt/iroha/build
      - run:
          name: codecov.io
          command: bash <(curl -s https://codecov.io/bash) -f $IROHA_BUILD/reports/gcovr.xml || echo "Codecov did not collect coverage reports"
      - run:
          name: execute sonar-scanner
          command: >
            if [ ! -z "$SONAR_TOKEN" ] && \
              [ ! -z "$CIRCLE_BUILD_NUM" ] && \
              [ ! -z "$CIRCLE_BRANCH" ]; then
              sonar-scanner \
                -Dsonar.login="${SONAR_TOKEN}" \
                -Dsonar.projectVersion="${CIRCLE_BUILD_NUM}" \
                -Dsonar.branch="${CIRCLE_BRANCH}"
            else
              echo "required env vars not found"
            fi
      - save_cache:
          key: sonar-{{ epoch }}
          paths:
            - ~/.sonar


  macos-build:
    macos:
      xcode: 9.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - brew-{{ arch }}
          paths:
            - Library/Caches/Homebrew
      - run:
          name: install dev dependencies
          command: brew install cmake boost postgres grpc autoconf automake libtool ccache
      - save_cache:
          key: brew-{{ arch }}-{{ epoch }}
          paths:
            - Library/Caches/Homebrew
      - restore_cache:
          keys:
            - build-cache-macos-{{ .Branch }}
            - build-cache-macos-
          paths:
            - ~/.ccache
      - restore_cache:
          keys:
            - external-macos-{{ .Branch }}
            - external-macos-
          paths:
            - external
      - run: ccache --show-stats
      - run:
          name: build
          command: |
            cmake -H. -Bbuild
            cmake --build build -- -j$(sysctl -n hw.ncpu)
      - save_cache:
          key: build-cache-macos-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.ccache
      - save_cache:
          key: build-cache-macos-{{ epoch }}
          paths:
            - ~/.ccache
      - save_cache:
          key: external-macos-{{ .Branch }}-{{ epoch }}
          paths:
            - external
      - save_cache:
          key: external-macos-{{ epoch }}
          paths:
            - external

      - run: ccache --show-stats


workflows:
  version: 2
  full_pipeline:
    jobs:
      # macos-build/build -> sonar -> dockerize
      - macos-build
      - build
      - sonar-pr:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - master
            tags:
              # do not invoke sonar-pr for tags
              ignore: /.*/
      # invoke sonar-release whenever anything to master, develop is pushed
      # or any commit tagged with v[\.0-9]+.*
      - sonar-release:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /v[\.0-9]+.*/
